apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: poc-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: localhost:5000/fastapi-app:latest
        env:
        - name: POSTGRES_HOST
          valueFrom:
           configMapKeyRef: 
             name: postgres-configmap
             key: db_host        
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef: 
              name: postgres-configmap
              key: db_port  
        - name: POSTGRES_DB
          valueFrom:
           configMapKeyRef: 
             name: postgres-configmap
             key: db_name   
        - name: POSTGRES_USER
          valueFrom:
           secretKeyRef:
             name: postgres-secret
             key: postgres-root-username
        - name: POSTGRES_PASSWORD
          valueFrom:
           secretKeyRef:
             name: postgres-secret
             key: postgres-root-password
          
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  type: LoadBalancer  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
