apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: poc-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: localhost:5000/fastapi-app:latest
        env:
        - name: POSTGRES_HOST
          value: postgres-service
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: your_username
        - name: POSTGRES_PASSWORD
          value: your_password
        - name: POSTGRES_DB
          value: your_database_name
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  type: LoadBalancer  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
