apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: poc-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: your_username
        - name: POSTGRES_PASSWORD
          value: your_password
        - name: POSTGRES_DB
          value: your_database_name
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
