# secrets-reader-clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-reader-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: poc-kubernetes
roleRef:
  kind: ClusterRole
  name: secrets-reader
  apiGroup: rbac.authorization.k8s.io
